server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  # System logs
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/*log

  # Application logs from stack services
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost
        labels:
          job: prometheus
          service: prometheus
          __path__: /var/log/prometheus/*.log

  - job_name: grafana
    static_configs:
      - targets:
          - localhost
        labels:
          job: grafana
          service: grafana
          __path__: /var/log/grafana/*.log

  - job_name: alertmanager
    static_configs:
      - targets:
          - localhost
        labels:
          job: alertmanager
          service: alertmanager
          __path__: /var/log/alertmanager/*.log

  - job_name: blackbox
    static_configs:
      - targets:
          - localhost
        labels:
          job: blackbox
          service: blackbox
          __path__: /var/log/blackbox/*.log

  - job_name: karma
    static_configs:
      - targets:
          - localhost
        labels:
          job: karma
          service: karma
          __path__: /var/log/karma/*.log

  - job_name: loki
    static_configs:
      - targets:
          - localhost
        labels:
          job: loki
          service: loki
          __path__: /var/log/loki/*.log

  - job_name: vscode
    static_configs:
      - targets:
          - localhost
        labels:
          job: vscode
          service: vscode
          __path__: /var/log/vscode/*.log

  # Docker container logs (if available)
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          service: docker
          __path__: /var/lib/docker/containers/*/*-json.log

  # Journal logs (systemd)
  - job_name: journal
    journal:
      json: false
      max_age: 12h
      path: /var/log/journal
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
      - source_labels: ['__journal__hostname']
        target_label: 'hostname'

  # Generic catch-all for any other logs
  - job_name: catchall
    static_configs:
      - targets:
          - localhost
        labels:
          job: catchall
          __path__: /var/log/**/*.log

  # Home Assistant specific logs (if accessible)
  - job_name: homeassistant
    static_configs:
      - targets:
          - localhost
        labels:
          job: homeassistant
          service: homeassistant
          __path__: /var/log/homeassistant/*.log

  # Supervisor logs (if accessible)
  - job_name: supervisor
    static_configs:
      - targets:
          - localhost
        labels:
          job: supervisor
          service: supervisor
          __path__: /var/log/supervisor/*.log 