global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:

  ##############################
  # When running as standalone #
  ##############################

  # Home Assistant Core (standalone mode) - DISABLED in addon mode
  # - job_name: 'hass_core_standalone'
  #   static_configs:
  #     - targets: ['${HOME_ASSISTANT_IP:-your-home-assistant-ip}:${HOME_ASSISTANT_PORT:-8123}']
  #   metrics_path: '/api/prometheus'
  #   scrape_interval: 30s
  #   scrape_timeout: 10s
  #   authorization:
  #     type: Bearer
  #     credentials: "${HOME_ASSISTANT_TOKEN:-your-long-lived-access-token-here}"


  #########################
  # When running as addon #
  #########################

  # Home Assistant HTTP-based add-ons
  - job_name: 'hass_addons_http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      # Home Assistant Core
      - targets:
        - 'a0d7b954-homeassistant:8123'
        labels:
          group: 'home_assistant'
          service: 'core_api'
          __param_target: 'http://a0d7b954-homeassistant:8123/api/'
      - targets:
        - 'a0d7b954-homeassistant:8123'
        labels:
          group: 'home_assistant'
          service: 'core_root'
          __param_target: 'http://a0d7b954-homeassistant:8123/'
      # Common add-ons HTTP endpoints
      - targets:
        - 'a0d7b954-zigbee2mqtt:8080'
        - 'a0d7b954-zwavejs2mqtt:8091'
        - 'a0d7b954-esphome:6052'
        - 'a0d7b954-node-red:1880'
        - 'a0d7b954-grafana:3000'
        - 'a0d7b954-nginx-proxy-manager:81'
        - 'a0d7b954-traefik:8080'
        - 'a0d7b954-portainer:9000'
        - 'a0d7b954-pihole:80'
        - 'a0d7b954-adguard:3000'
        - 'a0d7b954-vaultwarden:80'
        - 'a0d7b954-jellyfin:8096'
        - 'a0d7b954-plex:32400'
        - 'a0d7b954-sonarr:8989'
        - 'a0d7b954-radarr:7878'
        - 'a0d7b954-lidarr:8686'
        - 'a0d7b954-readarr:8787'
        - 'a0d7b954-sabnzbd:8080'
        - 'a0d7b954-qbittorrent:8080'
        - 'a0d7b954-transmission:9091'
        - 'a0d7b954-deluge:8112'
        - 'a0d7b954-jackett:9117'
        - 'a0d7b954-prowlarr:9696'
        - 'a0d7b954-ombi:3579'
        - 'a0d7b954-tautulli:8181'
        - 'a0d7b954-overseerr:5055'
        - 'a0d7b954-bazarr:6767'
        - 'a0d7b954-whisparr:6969'
        - 'a0d7b954-emby:8096'
        - 'a0d7b954-kodi:8080'
        - 'a0d7b954-homebridge:8581'
        - 'a0d7b954-habridge:8080'
        - 'a0d7b954-deconz:80'
        - 'a0d7b954-phoscon:80'
        - 'a0d7b954-appdaemon:5050'
        - 'a0d7b954-hass-configurator:3218'
        - 'a0d7b954-google-drive-backup:8080'
        - 'a0d7b954-dropbox-sync:8080'
        - 'a0d7b954-syncthing:8384'
        - 'a0d7b954-resilio-sync:8888'
        - 'a0d7b954-nextcloud:8080'
        - 'a0d7b954-seafile:8000'
        - 'a0d7b954-owncloud:8080'
        - 'a0d7b954-webdav:8080'
        - 'a0d7b954-calibre:8080'
        - 'a0d7b954-ubooquity:2202'
        labels:
          group: 'hass_addons_http'
          service: 'http'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115

  # Home Assistant TCP-based add-ons
  - job_name: 'hass_addons_tcp'
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      # Database services
      - targets:
        - 'a0d7b954-mariadb:3306'
        - 'a0d7b954-postgresql:5432'
        - 'a0d7b954-redis:6379'
        - 'a0d7b954-influxdb:8086'
        labels:
          group: 'hass_addons_tcp'
          service: 'databases'
      # MQTT and messaging
      - targets:
        - 'a0d7b954-mosquitto:1883'
        - 'a0d7b954-mosquitto:8883'
        labels:
          group: 'hass_addons_tcp'
          service: 'mqtt'
      # File sharing and backup
      - targets:
        - 'a0d7b954-samba:139'
        - 'a0d7b954-samba:445'
        - 'a0d7b954-ftp:21'
        - 'a0d7b954-rsync:873'
        - 'a0d7b954-backup:2020'
        labels:
          group: 'hass_addons_tcp'
          service: 'file_sharing'
      # VPN and networking
      - targets:
        - 'a0d7b954-wireguard:51820'
        labels:
          group: 'hass_addons_tcp'
          service: 'vpn'
      # SSH
      - targets:
        - 'a0d7b954-ssh:22'
        labels:
          group: 'hass_addons_tcp'
          service: 'ssh'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115

  # Home Assistant Core
  - job_name: 'hass_core'
    static_configs:
      - targets: ['a0d7b954-homeassistant:8123']
        labels:
          group: 'home_assistant'
          service: 'core'
    metrics_path: '/api/prometheus'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Home Assistant Supervisor
  - job_name: 'hass_supervisor'
    static_configs:
      - targets: ['supervisor:80']
        labels:
          group: 'home_assistant'
          service: 'supervisor'
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          group: 'stack'
          service: 'prometheus'
    scrape_interval: 15s

  # Alertmanager
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['localhost:9093']
        labels:
          group: 'stack'
          service: 'alertmanager'
    scrape_interval: 15s

  # Blackbox Exporter
  - job_name: 'blackbox_exporter'
    static_configs:
      - targets: ['localhost:9115']
        labels:
          group: 'stack'
          service: 'blackbox_exporter'
    scrape_interval: 15s

  # Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['localhost:3000']
        labels:
          group: 'stack'
          service: 'grafana'
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Loki metrics
  - job_name: 'loki'
    static_configs:
      - targets: ['localhost:3100']
        labels:
          group: 'stack'
          service: 'loki'
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Karma metrics
  - job_name: 'karma'
    static_configs:
      - targets: ['localhost:8080']
        labels:
          group: 'stack'
          service: 'karma'
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Internal addon services HTTP health checks
  - job_name: 'addon_services'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets: ['localhost:8080']  # Karma UI
        labels:
          group: 'stack'
          service: 'karma_ui'
      - targets: ['localhost:8443']  # VS Code
        labels:
          group: 'stack'
          service: 'vscode'
      - targets: ['localhost:80']    # NGINX status
        labels:
          group: 'stack'
          service: 'nginx'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115
