server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml
  sync_period: 10s

clients:
  - url: http://localhost:3100/loki/api/v1/push
    batchwait: 1s
    batchsize: 1024
    timeout: 10s

scrape_configs:
  # NGINX error logs (available in container)
  - job_name: nginx
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          service: nginx
          __path__: /var/log/nginx/error.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2}) \[(?P<level>\w+)\] (?P<pid>\d+)#(?P<tid>\d+): \*(?P<connection>\d+) (?P<message>.*)$'
      - timestamp:
          source: timestamp
          format: "2006/01/02 15:04:05"
      - labels:
          level:
          connection:

  # Prometheus logs
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost
        labels:
          job: prometheus
          service: prometheus
          __path__: /var/log/prometheus/prometheus.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d+Z) (?P<level>\w+) (?P<component>\w+)=(?P<component_value>[^ ]+) (?P<message>.*)$'
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - labels:
          level:
          component:

  # Alertmanager logs
  - job_name: alertmanager
    static_configs:
      - targets:
          - localhost
        labels:
          job: alertmanager
          service: alertmanager
          __path__: /var/log/alertmanager/alertmanager.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d+Z) (?P<level>\w+) (?P<component>\w+)=(?P<component_value>[^ ]+) (?P<message>.*)$'
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - labels:
          level:
          component:

  # Grafana logs
  - job_name: grafana
    static_configs:
      - targets:
          - localhost
        labels:
          job: grafana
          service: grafana
          __path__: /var/log/grafana/grafana.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d+Z) (?P<level>\w+) (?P<logger>\w+) (?P<message>.*)$'
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - labels:
          level:
          logger:

  # Blackbox Exporter logs
  - job_name: blackbox
    static_configs:
      - targets:
          - localhost
        labels:
          job: blackbox
          service: blackbox
          __path__: /var/log/blackbox/blackbox.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d+Z) (?P<level>\w+) (?P<component>\w+)=(?P<component_value>[^ ]+) (?P<message>.*)$'
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - labels:
          level:
          component:

  # Karma logs
  - job_name: karma
    static_configs:
      - targets:
          - localhost
        labels:
          job: karma
          service: karma
          __path__: /var/log/karma/karma.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d+Z) (?P<level>\w+) (?P<message>.*)$'
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - labels:
          level:

  # Loki logs
  - job_name: loki
    static_configs:
      - targets:
          - localhost
        labels:
          job: loki
          service: loki
          __path__: /var/log/loki/loki.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d+Z) (?P<level>\w+) (?P<component>\w+)=(?P<component_value>[^ ]+) (?P<message>.*)$'
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - labels:
          level:
          component:

  # VS Code logs
  - job_name: vscode
    static_configs:
      - targets:
          - localhost
        labels:
          job: vscode
          service: vscode
          __path__: /var/log/vscode/vscode.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d+Z) (?P<level>\w+) (?P<message>.*)$'
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - labels:
          level:
    