apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    uid: influxdb
    access: proxy
    url: http://localhost:8086
    isDefault: true
    editable: true
    jsonData:
      version: Flux
      organization: my-org
      defaultBucket: my-bucket
      httpMode: POST
    secureJsonData:
      token: my-token 