# =============================================================================
# CONFIGURATION FILES DEFINITION
# =============================================================================
# This YAML file defines all configuration files handled by the sync tools
# 
# Structure:
#   filename_pattern:
#     type: TEMPLATE_FILE | STATIC_FILE | GENERATED_FILE | GENERATED_TRACKABLE
#     runtime_path: path within /etc/ in container (runtime location)
#     source_path: path in git repository (source location) 
#     extracted_path: directory path for extraction (extracted location)
#     description: human-readable description
#
# File Types:
#   TEMPLATE_FILE:      Has source template (compare against ./prometheus-stack/filename)
#   STATIC_FILE:        Static file copied from rootfs (compare against ./prometheus-stack/rootfs/etc/runtime_path/filename)  
#   GENERATED_FILE:     Generated at runtime (no source comparison, only runtime)
#   GENERATED_TRACKABLE: Generated at runtime but track manual changes (compare extracted vs runtime with filtering)
# =============================================================================

# Dashboard Files
"*.json":
  type: STATIC_FILE
  runtime_path: grafana/provisioning/dashboards
  source_path: prometheus-stack/rootfs/etc/grafana/provisioning/dashboards
  extracted_path: dashboards
  description: "DEPLOYMENT: Copied during Docker build from rootfs/etc/grafana/provisioning/dashboards/ → /etc/grafana/provisioning/dashboards/ - Grafana dashboard JSON definitions"

"dashboard-provider.yml":
  type: STATIC_FILE
  runtime_path: grafana/provisioning/dashboards
  source_path: prometheus-stack/rootfs/etc/grafana/provisioning/dashboards
  extracted_path: dashboards
  description: "DEPLOYMENT: Copied during Docker build from rootfs/etc/grafana/provisioning/dashboards/ → /etc/grafana/provisioning/dashboards/ - Grafana dashboard provider config"

# Prometheus Files
"prometheus.yml":
  type: TEMPLATE_FILE
  runtime_path: prometheus
  source_path: prometheus-stack
  extracted_path: prometheus
  description: "DEPLOYMENT: Copied during Docker build from prometheus-stack/prometheus.yml → /etc/prometheus/prometheus.yml via Dockerfile COPY command - Main Prometheus configuration template"

"*.yml":
  type: STATIC_FILE
  runtime_path: prometheus
  source_path: prometheus-stack/rootfs/etc/prometheus
  extracted_path: prometheus
  description: "DEPLOYMENT: Copied during Docker build from rootfs/etc/prometheus/ → /etc/prometheus/ - Prometheus alerting and recording rule files"
  priority: 2  # Lower priority than specific prometheus.yml match

# Grafana Files
"grafana.ini":
  type: TEMPLATE_FILE
  runtime_path: grafana
  source_path: prometheus-stack
  extracted_path: grafana
  description: "DEPLOYMENT: Copied during Docker build from prometheus-stack/grafana.ini → /etc/grafana/grafana.ini via Dockerfile COPY command - Grafana server configuration template"

# Grafana Datasource Files (special case - different runtime_path)
"prometheus.yml@datasources":
  type: STATIC_FILE
  runtime_path: grafana/provisioning/datasources
  source_path: prometheus-stack/rootfs/etc/grafana/provisioning/datasources
  extracted_path: grafana
  description: "DEPLOYMENT: Copied during Docker build from rootfs/etc/grafana/provisioning/datasources/ → /etc/grafana/provisioning/datasources/ - Grafana Prometheus datasource configuration"
  match_path: "*/provisioning/datasources/*"

# Blackbox Files
"blackbox.yml":
  type: TEMPLATE_FILE
  runtime_path: blackbox_exporter
  source_path: prometheus-stack
  extracted_path: blackbox
  description: "DEPLOYMENT: Copied during Docker build from prometheus-stack/blackbox.yml → /etc/blackbox_exporter/blackbox.yml via Dockerfile COPY command - Blackbox Exporter configuration template"

# Loki Files
"loki.yml":
  type: TEMPLATE_FILE
  runtime_path: loki
  source_path: prometheus-stack
  extracted_path: loki
  description: "DEPLOYMENT: Copied during Docker build from prometheus-stack/loki.yml → /etc/loki/loki.yml via Dockerfile COPY command - Loki log aggregation configuration template"

# Alertmanager Files
"alertmanager.yml":
  type: GENERATED_TRACKABLE
  runtime_path: alertmanager
  source_path: ""
  extracted_path: alerting
  description: "DEPLOYMENT: Generated at container startup by /etc/cont-init.d/00-init.sh from /data/options.json → /etc/alertmanager/alertmanager.yml - Alertmanager routing and notification config"

# Karma Files
"karma.yml":
  type: GENERATED_TRACKABLE
  runtime_path: karma
  source_path: ""
  extracted_path: karma
  description: "DEPLOYMENT: Generated at container startup by /etc/cont-init.d/00-init.sh (static template) → /etc/karma/karma.yml - Karma alert dashboard configuration"

# NGINX Files
"nginx.conf":
  type: STATIC_FILE
  runtime_path: nginx
  source_path: prometheus-stack/rootfs/etc/nginx
  extracted_path: nginx
  description: "DEPLOYMENT: Copied during Docker build from rootfs/etc/nginx/ → /etc/nginx/ - NGINX main server configuration"

"ingress.conf":
  type: STATIC_FILE
  runtime_path: nginx/servers
  source_path: prometheus-stack/rootfs/etc/nginx/servers
  extracted_path: nginx
  description: "DEPLOYMENT: Copied during Docker build from rootfs/etc/nginx/servers/ → /etc/nginx/servers/ - NGINX ingress routing configuration" 