# =============================================================================
# INFLUXDB STACK CONFIGURATION FILES DEFINITION
# =============================================================================
# PURPOSE: Centralized configuration for all config files in the InfluxDB Stack
# USAGE:   Used by sync-tools scripts for consistent file handling
#
# This YAML file defines how each configuration file should be handled:
#
# FILE TYPES:
#   TEMPLATE_FILE:      Has source template (compare against ./influxdb-stack/filename)
#   STATIC_FILE:        Static file copied from rootfs (compare against ./influxdb-stack/rootfs/etc/runtime_path/filename)
#   GENERATED_TRACKABLE: Generated at runtime but we want to track manual changes
#
# PROPERTIES:
#   type:            File type (see above)
#   runtime_path:    Path in container (/etc/runtime_path/filename)
#   source_path:     Path in git repository (for TEMPLATE_FILE and STATIC_FILE)
#   extracted_path:  Directory name in ssh-extracted-configs/
#   description:     How this file gets deployed and what it does
#   priority:        Processing order (1=highest, 5=lowest)
#   match_path:      Special matching pattern for disambiguation
# =============================================================================

# Dashboard Files
"home.json":
  type: STATIC_FILE
  runtime_path: grafana/provisioning/dashboards
  source_path: influxdb-stack/rootfs/etc/grafana/provisioning/dashboards
  extracted_path: dashboards/dashboards
  description: "DEPLOYMENT: Copied during Docker build from influxdb-stack/rootfs/etc/grafana/provisioning/dashboards/home.json → /etc/grafana/provisioning/dashboards/home.json - Main InfluxDB Stack overview dashboard"
  priority: 3

"*.json":
  type: STATIC_FILE
  runtime_path: grafana/provisioning/dashboards
  source_path: influxdb-stack/rootfs/etc/grafana/provisioning/dashboards
  extracted_path: dashboards/dashboards
  description: "DEPLOYMENT: Copied during Docker build from influxdb-stack/rootfs/etc/grafana/provisioning/dashboards/*.json → /etc/grafana/provisioning/dashboards/*.json - Grafana dashboard definitions"
  priority: 4

# Grafana Configuration Files
"grafana.ini":
  type: TEMPLATE_FILE
  runtime_path: grafana
  source_path: influxdb-stack
  extracted_path: grafana
  description: "DEPLOYMENT: Copied during Docker build from influxdb-stack/grafana.ini → /etc/grafana/grafana.ini via Dockerfile COPY command - Grafana server configuration template"
  priority: 1

"influxdb.yml":
  type: STATIC_FILE
  runtime_path: grafana/provisioning/datasources
  source_path: influxdb-stack/rootfs/etc/grafana/provisioning/datasources
  extracted_path: grafana/datasources
  description: "DEPLOYMENT: Copied during Docker build from influxdb-stack/rootfs/etc/grafana/provisioning/datasources/influxdb.yml → /etc/grafana/provisioning/datasources/influxdb.yml - InfluxDB datasource configuration"
  priority: 2

# NGINX Configuration Files
"nginx.conf":
  type: STATIC_FILE
  runtime_path: nginx
  source_path: influxdb-stack/rootfs/etc/nginx
  extracted_path: nginx
  description: "DEPLOYMENT: Copied during Docker build from influxdb-stack/rootfs/etc/nginx/nginx.conf → /etc/nginx/nginx.conf - Main NGINX configuration"
  priority: 2

"ingress.conf":
  type: STATIC_FILE
  runtime_path: nginx/servers
  source_path: influxdb-stack/rootfs/etc/nginx/servers
  extracted_path: nginx/servers
  description: "DEPLOYMENT: Copied during Docker build from influxdb-stack/rootfs/etc/nginx/servers/ingress.conf → /etc/nginx/servers/ingress.conf - NGINX ingress routing configuration"
  priority: 2

# Dashboard Provider Configuration
"dashboard-provider.yml":
  type: STATIC_FILE
  runtime_path: grafana/provisioning/dashboards
  source_path: influxdb-stack/rootfs/etc/grafana/provisioning/dashboards
  extracted_path: dashboards/providers
  description: "DEPLOYMENT: Copied during Docker build from influxdb-stack/rootfs/etc/grafana/provisioning/dashboards/dashboard-provider.yml → /etc/grafana/provisioning/dashboards/dashboard-provider.yml - Grafana dashboard provider configuration"
  priority: 2

# Generic YAML files (catch-all for any other .yml files)
"*.yml":
  type: STATIC_FILE
  runtime_path: ""
  source_path: ""
  extracted_path: ""
  description: "DEPLOYMENT: Various YAML configuration files - deployment method varies by location"
  priority: 5 